name: find-breakpoints
on:
 push:
  paths-ignore:
    - '.github/workflows/**'
    - 'README.md'
jobs:
  basic-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Find breakpoints
      run: |
        ! grep -r "breakpoint()" --include=*.py || false
        echo "Exit Status:" $?
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
